name: Tweet Trending Hashtags

on:
  schedule:
    - cron: "0 */4 * * *"  # Run every 4 hours

jobs:
  run-tweet-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          pip install tweepy requests  # Install required packages

      - name: Run script
        run: |
          python main.py  # Replace with your script name
