name: YouTube Milestone Bot

on:
  schedule:
    - cron: "0 */4 * * *"  # This runs the job every 4 hours
  workflow_dispatch: # Allows manual trigger if needed

permissions:
  contents: write

jobs:
  tweet_milestone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests

    - name: Run YouTube Milestone Bot
      run: python main.py  # Ensure this matches your script's name

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add channel_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update channel data [skip ci]" && git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git)
